services:
  traefik:
    image: traefik:v3.6
    container_name: traefik
    command:
      # for traefik commands configuration options 
      # https://doc.traefik.io/traefik/reference/install-configuration/boot-environment/
      #- "--api.debug=true"
      #- "--log.level=DEBUG"
      - "--api.dashboard=true"
      - "--api.insecure=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/tls_config.yml"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: traefik_tls_yml
        target: /etc/traefik/tls_config.yml
    secrets:
      - traefik_ssl_key
      - traefik_ssl_cert
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik-dashboard.hung.org`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

  #whoami:
  #  image: traefik/whoami
  #  container_name: whoami
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
  #    - "traefik.http.routers.whomai.entrypoints=web"

  n8n:
    image: docker.n8n.io/n8nio/n8n:2.10.4
    container_name: n8n
    #domainname: n8n.hung.org
    #ports:
    #  - 5678:5678
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      #- N8N_LISTEN_ADDRESS="0.0.0.0"
      - GENERIC_TIMEZONE="Europe/London"
      - TZ="Europe/London"
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_HOST=n8n.hung.org
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.hung.org/
      #- N8N_SECURE_COOKIE=false
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`n8n.hung.org`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls=true
      #- traefik.http.middlewares.n8n.headers.SSLRedirect=true
      #- traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      #- traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      #- traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      #- traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      #- traefik.http.middlewares.n8n.headers.SSLHost=hung.org
      #- traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      #- traefik.http.middlewares.n8n.headers.STSPreload=true      

  ollama:
    image: ollama/ollama:0.17.7
    container_name: ollama
    #ports:
    #  - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_KEEP_LIVE=4h

volumes:
  ollama_data:
    name: "ollama-data"
  n8n_data:
    name: "n8n-data"

secrets:
  traefik_ssl_key:
    file: certs/traefik.key
  traefik_ssl_cert:
    file: certs/traefik.crt

configs:
  traefik_tls_yml:
    content: |
      tls:
        certificates:
          - keyFile: /run/secrets/traefik_ssl_key
            certFile: /run/secrets/traefik_ssl_cert